name: CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: budget
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://user:password@localhost:5432/budget
      JWT_SECRET: testsecret

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Prisma generate
        run: npx prisma generate

      - name: Run migrations
        run: npx prisma migrate deploy

      - name: Lint (optional)
        run: npm run lint || echo "No lint configured"

      - name: Run tests (optional)
        run: npm test || echo "No tests configured"

      - name: Build app
        run: npm run build || echo "No build step"

      - name: Build Docker Image 
        run: docker build  -t budget-api .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag budget-api ${{ secrets.DOCKER_USERNAME }}/budget-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/budget-api:latest